### PR TITLE
Quote attribution fixes

### PR DESCRIPTION
**Pull request by RaceProUK**
Two fixes:

- `7a8fe3b` - Add the topic/post attribution to new posts as well as posts being edited
- `bad86e4` - A change to the condition tested to determine whether to include topic and post to always insert it if the data is available

### CODE REVIEW

**Comment by julianlam** [comment]
Thanks for the contribution! :smile:

**Comment by pichalite** [comment]
@RaceProUK @julianlam the changes made in the PR are adding an unnecessary link to the topic that was quoted.    "user said in [topic title]"

image

**Comment by julianlam** [comment]
Yes, agreed, the topic title should only be appended if the quote comes from a different topic...

**Comment by RaceProUK** [comment]
What if you're quoting multiple posts in the same topic? Each link goes to the post the quote is from.

**Comment by pichalite** [comment]
Hmm good point. In that case I think the UI needs to be changed to remove the link next to the post time and make it similar for replies as well.

**Comment by julianlam** [comment]
> In that case I think the UI needs to be changed to remove the link next to the post time 

If anything, I think this looks better than having it in the post body...

**Pull request merged**
