### PR TITLE
Fix category selector dropdown position

### PR DESCRIPTION
**Pull request by lots0logs**
@barisusakli

### CODE REVIEW

**Comment by barisusakli** [comment]
What does this fix?

The changes for the composer are on our community.

image


If the composer is smaller than window.height() /2 then it gets a dropup class automatically.

image

**Comment by pitaj** [comment]
I just want to mention that the dropup does not work when the composer is maximized.

**Comment by lots0logs** [comment]
The problem is in Lavendar (and this I assume in Vanilla as well). I already fixed it on our site so you cant see it but the button appears at the beginning of its container instead of floating right like it does in Persona. Fixing that issue brings with it a new issue with the menu itself, it renders halfway off-screen so I addressed that in this PR as well.

**Comment by lots0logs** [comment]
@barisusakli Hope this helps:

### Before
2017-06- 5_01-13-47-am

### After
2017-06- 4_09-58-22-pm

**Comment by lots0logs** [comment]
@barisusakli *bump*

**Pull request merged**
