### PR TITLE
remove global call to templates and require benchpress

### PR DESCRIPTION
**Pull request by pichalite**

### CODE REVIEW

**Comment by pitaj** [comment]
I'm not even sure why this function exists since `app.parseAndTranslate` does the same thing AFAIK.

**Comment by barisusakli** [comment]
Was probably added before app.parseAndTranslate existed.

**Comment by pitaj** [comment]
Right, so just change it to use `app.parseAndTranslate` instead of the custom function

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-composer-default/commit/5b407f266410db07838657bc9d73d134625945de

**Pull request merged**
