### PR TITLE
Fix quote attribution for topic titles that include [ or ]

### PR DESCRIPTION
**Pull request by RaceProUK**
Specifically, a `[` at the start of the title or a `]` at the end of a title, as it would otherwise interfere with either the Markdown parsing or the translation system

### CODE REVIEW

**Comment by RaceProUK** [comment]
Wait to merge: need to fix some JS weirdness first

**Comment by RaceProUK** [comment]
OK; should be good to go now

**Comment by BenLubar** [comment]
RaceProUK/nodebb-plugin-composer-default#1

A pull request within a pull request :astonished:

**Comment by julianlam** [comment]
:laughing: will wait for merge before testing :smile:

**Comment by RaceProUK** [comment]
It's PR-ception! :smile:

**Comment by RaceProUK** [comment]
I think, unless we find something weird and unexpected, this is good to go :smile:

**Pull request merged**
