### PR TITLE
remove submit button dropdown for regular users

### PR DESCRIPTION
**Pull request by pichalite**
no point it displaying the dropdown with only one option that cannot be changed.

### CODE REVIEW

**Comment by julianlam** [comment]
Hm... hooks can add items to this dropdown... case in point, question-and-answer.

Might need a bit more logic than just admin/mod detection :frowning:

**Comment by pichalite** [comment]
I knew it... I was thinking about that right before submitting the pull request.

**Comment by pichalite** [comment]
I need to be better at this :disappointed:

**Comment by psychobunny** [comment]
Tbh I don't like the dropdown at all

1. No plugins: empty dropdown for regular user
2. Maybe you have one plugin, but why would you want a dropdown just for one option?

I've been thinking about it... we overabuse dropdowns everywhere for 1-2 options. If you have an idea I'm happy to brainstorm

**Pull request closed without merging**
