### PR TITLE
design changes for composer on mobile

### PR DESCRIPTION
**Pull request by pichalite**
does not fix all issues but provides more space for editor on mobile

### CODE REVIEW

**Comment by julianlam** [comment]
Sign offs received from @psychobunny and myself.

**Comment by pichalite** [comment]
one moment while I add "active" highlight for category selector

**Comment by pichalite** [comment]
done

**Comment by psychobunny** [comment]
I'd like to publicly say, awesome job - this works quite well on android and I know you're testing this on iPhone too.

**Pull request merged**
