### PR TITLE
Let's try this with CSS

### PR DESCRIPTION
**Pull request by pitaj**
@julianlam This is the *other* PR with more changes, including using CSS to do most of the stuff instead of JS. There are also a few changes on mobile, like hiding the tags input (it's hard to use on mobile anyways) and showing the formatting stuff always. Also, removed the use of `autosize` on the `textarea` by making the textarea scroll instead of the container.

### CODE REVIEW

**Comment by pitaj** [comment]
@julianlam Any comments on this? Are you not prepared to switch to CSS only? I can't think of anything than this will break.

**Comment by pitaj** [comment]
Yeah, I flat out removed all of the data from that hook. I figured the listener could get that data itself. It makes the animation faster by not needing to calculate the height itself with every mousemove occurrence. 

I feel like refactor could use some CSS magic as well, if its setting the height with every mousemove.

**Comment by julianlam** [comment]
Would be good to get @drewdotpro in for his opinion

**Comment by pitaj** [comment]
I'd like @drewdotpro to respond soon. Waiting two weeks for a response is annoying.

**Comment by pitaj** [comment]
Okay so I've waited almost a month for @drewdotpro to respond and he has not -_- this is annoying.

Anyways, @julian, just let me quickly write up a fix for redactor. I'll send a PR to that repo when I'm done.

**Comment by pichalite** [comment]
Can this be closed?

**Comment by pitaj** [comment]
@pichalite I'd like to keep it open just as a reminder. I plan on redoing this eventually.

**Pull request closed without merging**
