### PR TITLE
link to quoted post

### PR DESCRIPTION
**Pull request by segura2010**
We saw that an user want to put a link to the quoted post (https://community.nodebb.org/topic/6208/replies-to-comments-linking-back-to-original). On http://exo.do we did it because we wanted it, too. So We have decided to do a pull request with the changes we did. Feel free to change the arrow for the link or to change it as you want :)

### CODE REVIEW

**Comment by julianlam** [comment]
@segura2010 What is the behaviour of this link when pressed, does it scroll to the post, or does it reload the topic page?

**Comment by segura2010** [comment]
@julianlam it reloads the topic page. In our forum the majority of users don't use infinite scroll, so i simply reload the page. Is there any way to do it without reload? Will it work with paginated topics?

**Comment by Fastidious** [comment]
@julianlam for what i can see, they are doing it wrong (unless they want the ability to quote comments on a different thread), and reloading the whole page. NodeBB is so fast, that is hard to tell, but it seems a reload.

**Comment by julianlam** [comment]
`.scrollToPost` should work well (as long as you're linking to a pid)

**Comment by segura2010** [comment]
But, how can i do it with a link? The link to the quoted post is added to the reply, so i can't add JS on it. I think it could be done adding a method to hook filter:parse.post and play with it to add the proper JS (ajaxfy.go("/topic/TID/NAME/postIndex"))

**Comment by Fastidious** [comment]
@julianlam is there anything that can be done, to implement this one? I see it as a very handy way to propitiate engagement on a discussion.

**Comment by Fastidious** [comment]
Could this one be fixed as @julianlam recommended, so it has a better chance to be merged?

**Comment by martyalicante** [comment]
@Fastidious i think @segura2010 replied the problem that that link is html cause is procesed on post parse and not js. this could be done with another function on core and class id probably
waiting for staff reply

**Comment by julianlam** [comment]
I believe this PR is redundant now that we show the "Reply to" badge on direct replies.

**Comment by martyalicante** [comment]
Yes. This works with multiquote tho.

**Pull request closed without merging**
