### PR TITLE
Add element to autocomplete event data

### PR DESCRIPTION
**Pull request by frissdiegurke**
The problem with not passing the element for me:
I use an async socket call to fetch some information being used for the definition of the strategy.
So in case the event gets triggered before the socket call has been finished the strategy cannot be added.

### CODE REVIEW

**Comment by barisusakli** [comment]
If you port emoji-extended to javascript I can help btw, tried reading through it today gave me a headache.

**Comment by julianlam** [comment]
:+1: I want to add custom emoji support, but :coffee: scares me haha

**Comment by frissdiegurke** [comment]
Yes, I've a local rework of emoji-extended in progress. currently stalled due to uni stuff and working on another project...
I once posted an ETA somewhere, but clearly didn't make it xD
When it's finished it'll be purely javascript structured alike shortcuts plugin and moved into NodeBB-Community :wink:

But if you have some updates in the mean time to be modified within emoji-extended, don't bother creating those issues.
I'm gonna do my work then :coffee:.

**Comment by psychobunny** [comment]
> I once posted an ETA somewhere, but clearly didn't make it xD

Somebody is learning the NodeBB way ™

**Pull request merged**
